### ISSUE TITLE
No gui version?

### ISSUE THREAD

**Issue by kupietools** [shawnhooper/twitter-archive-to-wp#22]
Is there really absolutely no way to run this from the WP admin screens? My webhost makes SSH access pretty much impossible, I've lost hours just trying to SSH in and haven't even accomplished it successfully yet, doing this through the admin panel I could have it finished it in 5 minutes.

**Comment by shawnhooper** [comment]
@kupietools No, there's no UI for this package.  This is a WP-CLI utility. I wrote it for myself that was, because that's how I manage my websites.   

Keep in mind that the work to create a UI for this would have taken me hours more to do.   And this was a free project I put together and shared with the community.

Hope you find a tool that suits your needs.
